Clase #3

select * from producto;
select * from pedido;
select * from pago;

SELECT 
PRODUCTO.
ANIO,
VENTAS,
LAG(VENTAS) OVER ( PARTITION BY PRODUCTO ORDER BY ANIO ASC) VENTAS ANTERIORES, 
VENTAS-LAG(VENTAS) OVER ( PARTITION BY PRODUCTO ORDER BY ANIO ASC) CRECIMIENTO,
LEAD(VENTAS) OVER ( PARTITION BY PRODUCTO ORDER BY ANIO ASC) VENTAS_ POSTERIOR 
FROM (
SELECT PR.NOMBRE PRODUCTO,DP.CANTIDAD*D.PRECIO_UNIDAD VENTAS, EXTRACT(YEAR FROM P.FECHA_ENTREGA) ANIO 
FROM PEDIDO P
INNER JOIN DETALLE_PEDIDO DP
ON P.CODIGO_PEDIDO-DP.CODIGO_PEDIDO
INNER JOIN PRODUCTO PR
ON DP.CODIGO_PRODUCTO=PR.CODIGO_PRODUCTO
WHERE UPPER(P.ESTADO)= 'ENTREGADO'
)

4 MEJORES CLIENTES

SELECT * FROM CLIENTE

SELECT CLIENTE,VENTAS,NIVEL,
CASE WHEN NIVEL=1 THEN  'CATEGORIA A'
WHEN NIVEL=2 THEN 'CATEGORIA B'
WHEN NIVEL=3 THEN 'CATEGORIA C'
WHEN NIVEL=4 THEN 'CATEGORIA D'
END CATEGORIA
FROM (
SELECT CLIENTE, VENTAS,
NTILE(4) OVER (ORDER BY VENTAS DESC) AS NIVEL
FROM (
SELECT CL.NOMBRE_CLIENTE CLIENTE, SUM(DP.CANTIDAD*DP.PRECIO_UNIDAD) VENTAS 
FROM PEDIDO P
INNER JOIN DETALLE_PEDIDO DP
ON P.CODIGO_PEDIDO=DP.CODIGO_PEDIDO
INNER JOIN PRODUCTO PR 
ON DP.CODIGO_PRODUCTO=PR.CODIGO_PRODUCTO
INNER JOIN CLIENTE CL
ON P.CODIGO_CLIENTE=CL.CODIGO_CLIENTE
WHERE UPPER(P.ESTADO)='ENTREGADO'
GROUP BY CL.NOMBRE_CLIENTE
)
)



select * from oficina
SELECT codigo_oficina, ciudad
FROM oficina
GROUP BY codigo_oficina, ciudad;

2.	Actualice el límite de crédito de los clientes en un 25% adicional para los clientes que tengan un límite de crédito superior a  los $12000 y que viven en la ciudad de Miami.

select * from cliente

update cliente set LIMITE_CREDITO=(LIMITE_CREDITO*0.25)
where LIMITE_CREDITO>=12000
and lower(nvl(ciudad,'miami')) like '%miami%'