--------------------------------------------------------
--  File created - Monday-October-02-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "JARDINERIA"."CLIENTE" 
   (	"CODIGO_CLIENTE" NUMBER(*,0), 
	"NOMBRE_CLIENTE" VARCHAR2(50 BYTE), 
	"NOMBRE_CONTACTO" VARCHAR2(30 BYTE) DEFAULT NULL, 
	"APELLIDO_CONTACTO" VARCHAR2(30 BYTE) DEFAULT NULL, 
	"TELEFONO" VARCHAR2(15 BYTE), 
	"FAX" VARCHAR2(15 BYTE), 
	"LINEA_DIRECCION1" VARCHAR2(50 BYTE), 
	"LINEA_DIRECCION2" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"CIUDAD" VARCHAR2(50 BYTE), 
	"REGION" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"PAIS" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"CODIGO_POSTAL" VARCHAR2(10 BYTE) DEFAULT NULL, 
	"CODIGO_EMPLEADO_REP_VENTAS" NUMBER(*,0) DEFAULT NULL, 
	"LIMITE_CREDITO" NUMBER(15,2) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TRABAJO" ;
--------------------------------------------------------
--  DDL for Index SYS_C007073
--------------------------------------------------------

  CREATE UNIQUE INDEX "JARDINERIA"."SYS_C007073" ON "JARDINERIA"."CLIENTE" ("CODIGO_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TRABAJO" ;
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "JARDINERIA"."CLIENTE" ADD PRIMARY KEY ("CODIGO_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TRABAJO"  ENABLE;
  ALTER TABLE "JARDINERIA"."CLIENTE" MODIFY ("CIUDAD" NOT NULL ENABLE);
  ALTER TABLE "JARDINERIA"."CLIENTE" MODIFY ("LINEA_DIRECCION1" NOT NULL ENABLE);
  ALTER TABLE "JARDINERIA"."CLIENTE" MODIFY ("FAX" NOT NULL ENABLE);
  ALTER TABLE "JARDINERIA"."CLIENTE" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "JARDINERIA"."CLIENTE" MODIFY ("NOMBRE_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "JARDINERIA"."CLIENTE" MODIFY ("CODIGO_CLIENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "JARDINERIA"."CLIENTE" ADD FOREIGN KEY ("CODIGO_EMPLEADO_REP_VENTAS")
	  REFERENCES "JARDINERIA"."EMPLEADO" ("CODIGO_EMPLEADO") ENABLE;
